version: "3"

services:
  node:
    image: node:9
    volumes:
      - ./:/var/www/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: bash -c "while true; do echo ""; sleep 2; done;"
    working_dir: /var/www/app